### ISSUE TITLE
Question: output

### ISSUE THREAD

**Issue by ddey94** [gekkowarez/gekkoga#13]
What do these outputs exactly mean in context to each other? 

`
relativeProfit: 194.30317355494043,
  yearlyProfit: '48315.58376075',
  relativeYearlyProfit: '1030.38514508',`

and 

`max profit position: 0`

**Comment by generalectric** [comment]
These are output by gekko at the end of a backtest. Profit is the amount of profit your backtest generated. Relativeprofit is percentage of gain. Yearly profit is how much profit would have been generated during one year with current results. And relative yearly is the same as relativeprofit is to profit, only its yearly.
