### ISSUE TITLE
convertToDB.sh script

### ISSUE THREAD

**Issue by ecomkings** [gekkowarez/gekkoga#14]
Hello, 
I am trying to import data into Gekko but I can't seem to file the script to convert the JSON to a sqlite db file. I'd really appreciate anyone's help!

https://gekkowarez.com/tag/data-downloader/

**Comment by itenev** [comment]
There is an updated version of the script, mentioned in the comments section:

https://gist.github.com/agrimaldi/7115264ee9cc0bb9b4ffe4f89eb1fcdb

Haven't tested it myself tho
