### ISSUE TITLE
Error when trying talib-macd strat

### ISSUE THREAD

**Issue by Gebrax** [gekkowarez/gekkoga#17]
i have got following error when trying to run gekkoga using talib-macd rather than gekko nativemacd.

> node run.js -c config/configd.js
> Previous config found, loading...
> Loaded previous config from configd-USD_BTC.json
> Resuming previous run...
> Starting training with: 4 units
> { StatusCodeError: 500 - "Internal Server Error"
>     at new StatusCodeError (/home/danns/gekkoga/node_modules/request-promise-core/lib/errors.js:32:15)
>     at Request.plumbing.callback (/home/danns/gekkoga/node_modules/request-promise-core/lib/plumbing.js:104:33)
>     at Request.RP$callback [as _callback] (/home/danns/gekkoga/node_modules/request-promise-core/lib/plumbing.js:46:31)
>     at Request.self.callback (/home/danns/gekkoga/node_modules/request/request.js:186:22)
>     at Request.emit (events.js:159:13)
>     at Request.<anonymous> (/home/danns/gekkoga/node_modules/request/request.js:1163:10)
>     at Request.emit (events.js:159:13)
>     at IncomingMessage.<anonymous> (/home/danns/gekkoga/node_modules/request/request.js:1085:12)
>     at Object.onceWrapper (events.js:254:19)
>     at IncomingMessage.emit (events.js:164:20)
>     at endReadableNT (_stream_readable.js:1062:12)
>     at process._tickCallback (internal/process/next_tick.js:152:19)
>   name: 'StatusCodeError',
>   statusCode: 500,
>   message: '500 - "Internal Server Error"',
>   error: 'Internal Server Error',
>   options: 
>    { url: 'http://localhost:3000/api/backtest',
>      json: true,
>      body: { gekkoConfig: [Object], data: [Object] },
>      headers: { 'Content-Type': 'application/json' },
>      timeout: 900000,
>      method: 'POST',
>      callback: [Function: RP$callback],
>      transform: undefined,
>      simple: true,
>      resolveWithFullResponse: false,
>      transform2xxOnly: false },
>   response: 
>    IncomingMessage {
>      _readableState: 
>       ReadableState {
>         objectMode: false,
>         highWaterMark: 16384,
>         buffer: [BufferList],
>         length: 0,
>         pipes: null,
>         pipesCount: 0,
>         flowing: true,
>         ended: true,
>         endEmitted: true,
>         reading: false,
>         sync: true,
>         needReadable: false,
>         emittedReadable: false,
>         readableListening: false,
>         resumeScheduled: false,
>         destroyed: false,
>         defaultEncoding: 'utf8',
>         awaitDrain: 0,
>         readingMore: false,
>         decoder: null,
>         encoding: null },
>      readable: false,
>      domain: null,
>      _events: 
>       { end: [Array],
>         close: [Array],
>         data: [Function],
>         error: [Function] },
>      _eventsCount: 4,
>      _maxListeners: undefined,
>      socket: 
>       Socket {
>         connecting: false,
>         _hadError: false,
>         _handle: null,
>         _parent: null,
>         _host: 'localhost',
>         _readableState: [ReadableState],
>         readable: false,
>         domain: null,
>         _events: [Object],
>         _eventsCount: 9,
>         _maxListeners: undefined,
>         _writableState: [WritableState],
>         writable: false,
>         allowHalfOpen: false,
>         _bytesDispatched: 979,
>         _sockname: null,
>         _pendingData: null,
>         _pendingEncoding: '',
>         server: null,
>         _server: null,
>         parser: null,
>         _httpMessage: [ClientRequest],
>         read: [Function],
>         _consuming: true,
>         _idleTimeout: -1,
>         _idleNext: null,
>         _idlePrev: null,
>         _idleStart: 13637,
>         _destroyed: false,
>         [Symbol(asyncId)]: 24,
>         [Symbol(bytesRead)]: 176,
>         [Symbol(asyncId)]: 59,
>         [Symbol(triggerAsyncId)]: 53 },
>      connection: 
>       Socket {
>         connecting: false,
>         _hadError: false,
>         _handle: null,
>         _parent: null,
>         _host: 'localhost',
>         _readableState: [ReadableState],
>         readable: false,
>         domain: null,
>         _events: [Object],
>         _eventsCount: 9,
>         _maxListeners: undefined,
>         _writableState: [WritableState],
>         writable: false,
>         allowHalfOpen: false,
>         _bytesDispatched: 979,
>         _sockname: null,
>         _pendingData: null,
>         _pendingEncoding: '',
>         server: null,
>         _server: null,
>         parser: null,
>         _httpMessage: [ClientRequest],
>         read: [Function],
>         _consuming: true,
>         _idleTimeout: -1,
>         _idleNext: null,
>         _idlePrev: null,
>         _idleStart: 13637,
>         _destroyed: false,
>         [Symbol(asyncId)]: 24,
>         [Symbol(bytesRead)]: 176,
>         [Symbol(asyncId)]: 59,
>         [Symbol(triggerAsyncId)]: 53 },
>      httpVersionMajor: 1,
>      httpVersionMinor: 1,
>      httpVersion: '1.1',
>      complete: true,
>      headers: 
>       { 'content-type': 'text/plain; charset=utf-8',
>         'content-length': '21',
>         date: 'Sat, 30 Dec 2017 12:42:17 GMT',
>         connection: 'close' },
>      rawHeaders: 
>       [ 'Content-Type',
>         'text/plain; charset=utf-8',
>         'Content-Length',
>         '21',
>         'Date',
>         'Sat, 30 Dec 2017 12:42:17 GMT',
>         'Connection',
>         'close' ],
>      trailers: {},
>      rawTrailers: [],
>      upgrade: false,
>      url: '',
>      method: null,
>      statusCode: 500,
>      statusMessage: 'Internal Server Error',
>      client: 
>       Socket {
>         connecting: false,
>         _hadError: false,
>         _handle: null,
>         _parent: null,
>         _host: 'localhost',
>         _readableState: [ReadableState],
>         readable: false,
>         domain: null,
>         _events: [Object],
>         _eventsCount: 9,
>         _maxListeners: undefined,
>         _writableState: [WritableState],
>         writable: false,
>         allowHalfOpen: false,
>         _bytesDispatched: 979,
>         _sockname: null,
>         _pendingData: null,
>         _pendingEncoding: '',
>         server: null,
>         _server: null,
>         parser: null,
>         _httpMessage: [ClientRequest],
>         read: [Function],
>         _consuming: true,
>         _idleTimeout: -1,
>         _idleNext: null,
>         _idlePrev: null,
>         _idleStart: 13637,
>         _destroyed: false,
>         [Symbol(asyncId)]: 24,
>         [Symbol(bytesRead)]: 176,
>         [Symbol(asyncId)]: 59,
>         [Symbol(triggerAsyncId)]: 53 },
>      _consuming: true,
>      _dumped: false,
>      req: 
>       ClientRequest {
>         domain: null,
>         _events: [Object],
>         _eventsCount: 6,
>         _maxListeners: undefined,
>         output: [],
>         outputEncodings: [],
>         outputCallbacks: [],
>         outputSize: 0,
>         writable: true,
>         _last: true,
>         upgrading: false,
>         chunkedEncoding: false,
>         shouldKeepAlive: false,
>         useChunkedEncodingByDefault: true,
>         sendDate: false,
>         _removedConnection: false,
>         _removedContLen: false,
>         _removedTE: false,
>         _contentLength: null,
>         _hasBody: true,
>         _trailer: '',
>         finished: true,
>         _headerSent: true,
>         socket: [Socket],
>         connection: [Socket],
>         _header: 'POST /api/backtest HTTP/1.1\r\nContent-Type: application/json\r\nhost: localhost:3000\r\naccept: application/json\r\ncontent-length: 828\r\nConnection: close\r\n\r\n',
>         _onPendingData: [Function: noopPendingOutput],
>         agent: [Agent],
>         socketPath: undefined,
>         timeout: undefined,
>         method: 'POST',
>         path: '/api/backtest',
>         _ended: true,
>         res: [Circular],
>         aborted: undefined,
>         timeoutCb: [Function: emitTimeout],
>         upgradeOrConnect: false,
>         parser: null,
>         maxHeadersCount: null,
>         [Symbol(outHeadersKey)]: [Object] },
>      request: 
>       Request {
>         domain: null,
>         _events: [Object],
>         _eventsCount: 5,
>         _maxListeners: undefined,
>         body: '{"gekkoConfig":{"watch":{"exchange":"bitfinex","currency":"USD","asset":"BTC"},"paperTrader":{"slippage":0.05,"feeTaker":0.25,"feeMaker":0.25,"feeUsing":"taker","simulationBalance":{"asset":1,"currency":100},"reportRoundtrips":true,"enabled":true},"writer":{"enabled":false,"logpath":""},"tradingAdvisor":{"enabled":true,"method":"talib-macdori","candleSize":15,"historySize":66},"trader":{"enabled":false},"backtest":{"daterange":{"from":"2017-07-05 11:58","to":"2017-09-06 01:58"}},"performanceAnalyzer":{"riskFreeReturn":5,"enabled":true},"valid":true,"talib-macdori":{"historySize":66,"optInFastPeriod":5,"optInSlowPeriod":22,"optInSignalPeriod":22,"thresholds":{"up":"13.69","down":"-2.63"},"candleSize":15}},"data":{"candleProps":["close","start"],"indicatorResults":false,"report":true,"roundtrips":false,"trades":false}}',
>         headers: [Object],
>         timeout: 900000,
>         method: 'POST',
>         readable: true,
>         writable: true,
>         explicitMethod: true,
>         _qs: [Querystring],
>         _auth: [Auth],
>         _oauth: [OAuth],
>         _multipart: [Multipart],
>         _redirect: [Redirect],
>         _tunnel: [Tunnel],
>         _rp_resolve: [Function],
>         _rp_reject: [Function],
>         _rp_promise: [Promise],
>         _rp_callbackOrig: undefined,
>         callback: [Function],
>         _rp_options: [Object],
>         setHeader: [Function],
>         hasHeader: [Function],
>         getHeader: [Function],
>         removeHeader: [Function],
>         localAddress: undefined,
>         pool: {},
>         dests: [],
>         __isRequestRequest: true,
>         _callback: [Function: RP$callback],
>         uri: [Url],
>         proxy: null,
>         tunnel: false,
>         setHost: true,
>         originalCookieHeader: undefined,
>         _disableCookies: true,
>         _jar: undefined,
>         port: '3000',
>         host: 'localhost',
>         path: '/api/backtest',
>         _json: true,
>         httpModule: [Object],
>         agentClass: [Function],
>         agent: [Agent],
>         _started: true,
>         href: 'http://localhost:3000/api/backtest',
>         req: [ClientRequest],
>         ntick: true,
>         timeoutTimer: null,
>         response: [Circular],
>         originalHost: 'localhost:3000',
>         originalHostHeaderName: 'host',
>         responseContent: [Circular],
>         _destdata: true,
>         _ended: true,
>         _callbackCalled: true },
>      toJSON: [Function: responseToJSON],
>      caseless: Caseless { dict: [Object] },
>      read: [Function],
>      body: 'Internal Server Error' } }
> danns@danns-VirtualBox:~/gekkoga$ 

i also got another error in terminal1 which running gekko ui as follows : 

> node gekko --config config.js --backtest --ui
> 
>     ______   ________  __    __  __    __   ______
>    /      \ /        |/  |  /  |/  |  /  | /      \
>   /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
>   $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
>   $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
>   $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
>   $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
>   $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
>    $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/
> 
> 	Gekko v0.5.11
> 	I'm gonna make you rich, Bud Fox. 
> 
> 
> Serving Gekko UI on http://localhost:3000/
> 
>   <-- POST /api/backtest
>   <-- POST /api/backtest
>   <-- POST /api/backtest
>   <-- POST /api/backtest
> 2017-12-30 19:42:15 (INFO):	Setting up Gekko in backtest mode
> 2017-12-30 19:42:15 (INFO):	
> 2017-12-30 19:42:15 (INFO):	Setting up:
> 2017-12-30 19:42:15 (INFO):		 Trading Advisor
> 2017-12-30 19:42:15 (INFO):		 Calculate trading advice
> 2017-12-30 19:42:16 (INFO):	Setting up Gekko in backtest mode
> 2017-12-30 19:42:16 (INFO):	
> 2017-12-30 19:42:16 (INFO):	Setting up:
> 2017-12-30 19:42:16 (INFO):		 Trading Advisor
> 2017-12-30 19:42:16 (INFO):		 Calculate trading advice
> 2017-12-30 19:42:16 (INFO):		 Using the strategy: talib-macdori
> 2017-12-30 19:42:16 (INFO):	Setting up Gekko in backtest mode
> 2017-12-30 19:42:16 (INFO):	Setting up Gekko in backtest mode
> 2017-12-30 19:42:16 (INFO):	
> 2017-12-30 19:42:16 (INFO):	
> 2017-12-30 19:42:16 (INFO):	Setting up:
> 2017-12-30 19:42:16 (INFO):		 Trading Advisor
> 2017-12-30 19:42:16 (INFO):		 Calculate trading advice
> 2017-12-30 19:42:16 (INFO):	Setting up:
> 2017-12-30 19:42:16 (INFO):		 Trading Advisor
> 2017-12-30 19:42:16 (INFO):		 Calculate trading advice
> 2017-12-30 19:42:16 (INFO):		 Using the strategy: talib-macdori
> 2017-12-30 19:42:16 (WARN):	TULIP indicators could not be loaded, they will be unavailable.
> 2017-12-30 19:42:17 (INFO):		 Using the strategy: talib-macdori
> 2017-12-30 19:42:17 (INFO):		 Using the strategy: talib-macdori
> 2017-12-30 19:42:17 (WARN):	TULIP indicators could not be loaded, they will be unavailable.
> 
> /home/danns/gekko/core/talib.js:40
>             throw talibError + methodName + ' requires ' + paramName + '.';
>             ^
> Gekko was unable to configure talib indicator:
> 	macd requires optInFastPeriod.
>   xxx POST /api/backtest 500 7,206ms -
> 
>   Error: non-error thrown: Child process has died.
>       at Object.onerror (/home/danns/gekko/node_modules/koa/lib/context.js:105:40)
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:160:7)
> 
> 
> /home/danns/gekko/core/talib.js:40
>             throw talibError + methodName + ' requires ' + paramName + '.';
>             ^
> Gekko was unable to configure talib indicator:
> 	macd requires optInFastPeriod.
> 2017-12-30 19:42:17 (WARN):	TULIP indicators could not be loaded, they will be unavailable.
> 2017-12-30 19:42:17 (WARN):	TULIP indicators could not be loaded, they will be unavailable.
>   xxx POST /api/backtest 500 7,544ms -
> 
>   Error: non-error thrown: Child process has died.
>       at Object.onerror (/home/danns/gekko/node_modules/koa/lib/context.js:105:40)
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:160:7)
> 
> 
> /home/danns/gekko/core/talib.js:40
>             throw talibError + methodName + ' requires ' + paramName + '.';
>             ^
> Gekko was unable to configure talib indicator:
> 	macd requires optInFastPeriod.
> 
> /home/danns/gekko/core/talib.js:40
>             throw talibError + methodName + ' requires ' + paramName + '.';
>             ^
> Gekko was unable to configure talib indicator:
> 	macd requires optInFastPeriod.
>   xxx POST /api/backtest 500 7,652ms -
> 
>   Error: non-error thrown: Child process has died.
>       at Object.onerror (/home/danns/gekko/node_modules/koa/lib/context.js:105:40)
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:160:7)
> 
>   xxx POST /api/backtest 500 7,585ms -
> 
>   Error: non-error thrown: Child process has died.
>       at Object.onerror (/home/danns/gekko/node_modules/koa/lib/context.js:105:40)
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:160:7)

although error in terminal1 indicates that something wrong with my params definition, actually everything works fine when i running 'node gekko --config config.js --backtest'.
no error generated with message 'Gekko was unable to configure talib indicator'.

why is there any differences?has it something todo with how gekkoga connect to gekko config?
i have also defined params value for macd i gekko's config.

**Comment by viking76** [comment]
I think its not gekkoga script problem just in gekko try to install talib, but i have tested with tulind-macd with no success

**Comment by generalectric** [comment]
I'm assuming this issue is fixed thanks to a couple contributions. Going to close this.
