### ISSUE TITLE
Output explanations

### ISSUE THREAD

**Issue by Remonell** [gekkowarez/gekkoga#21]
The idea of this project is awesome. But I am not sure if it is successful or not because the output is not easy to interpret. There are many open questions about it.
For example:
What exactly is the Global maximum section? Why does the content change with every epoche? Why is my profit, relativeProfit, yearlyProfit, relativeYearlyProfit with every epoche the very same?
I really like about gekko, that you can easily see how much profit in % you made when you backtest. Would be great if you could implement that with your GA approach.
I think it would help if we had a general detailed explanation of every single point of the output. I am very thankful that you guys created this and I am of course in no position to ask you guys to give even more than you already did. But I would be very thankful for a documentation.

Kind regards

**Comment by generalectric** [comment]
Global maximum is the overall winner.... If your new maximum is greater than the previous all time high then it will change.... the one above that is the winner for the epoch. You are looking at overall winner so you dont see it update as much. Really gekkoga output would be really nice in frames side by side its just more effort than reward unfortunately.
