### ISSUE TITLE
RSI Not working? zero trades

### ISSUE THREAD

**Issue by Duwaynef** [gekkowarez/gekkoga#22]
Any way to make it work with RSI? constantly get zero trades, even with the sample-config it nets zero trades everytime...

**Comment by shimanotaka** [comment]
I have the same issue. I've tried different strategies and indicators, tried to limit the amount of variables, tried limiting the span of the variables to values that I know should produce trades, tried different currency pairs, both Ubuntu and Win10. Still 0 trades even if I leave it running all night. Attached two configs in case I've done something wrong in them.

[configs.zip](https://github.com/gekkowarez/gekkoga/files/1671190/configs.zip)

**Comment by generalectric** [comment]
I'm assuming this is no longer an issue, going to close it up
