### ISSUE TITLE
Mutate selection always chooses first element to mutate

### ISSUE THREAD

**Issue by kerbe6** [gekkowarez/gekkoga#29]
Problem is this line:
`let position = randomExt.integer(0, a.length);`

Should be:
`let position = randomExt.integer(a.length, 0);`

**Comment by kerbe6** [comment]
Actually should be:
let position = randomExt.integer(tmp.length, 0);

**Comment by kerbe6** [comment]
Actually it should be:
` let position = randomExt.integer(allProps.length - 1, 0);`

**Comment by kerbe6** [comment]
Also, I'd like to suggest an additional method of mutating a parameter. Instead of selecting a new parameter randomly, it would be nice if one could "jiggle" the existing parameter. Maybe by a user-defined percentage. For example:

```
maxMutataePercent = 0.1
newParam = oldParam * randomExt.float(maxMutatePercent, -maxMutatePercent)
```

**Comment by stereohelix** [comment]
Could you submit a pull request with these changes? 

The "jiggle" feature sounds interesting.

**Comment by generalectric** [comment]
@kerbe6 nice find would you like to PR it? That jiggle idea though... love it! Unfortunately my hands are tied atm so it wont be me that brings it to fruition, but id love to see it eventually.

**Comment by generalectric** [comment]
> Should be:
let position = randomExt.integer(a.length, 0);

@kerbe6 i finally had time to take a look. Good eye just one more thing though. Being 'a' is an object not an array, we get the length of the object keys Object.keys(a).length..... again very nice find im gonna go ahead and get the fix pushed.
