### ISSUE TITLE
timeout in config sample

### ISSUE THREAD

**Issue by dinankou** [gekkowarez/gekkoga#3]
> Correct in the sample the macd long short signal are hard coded.. So it's only doing candles thresholds and history size.
> You reminded me.. I'm going to move the timeout setting into the config. Keep in mind when this happens it will break configs.. So keep an eye out for commits where Sample-config.js has new stuff added to it.. Because you will need to add them to your config in the event you update

putting this here so it doesnt mix with thread #2 

what do you mean by "it will break configs" ?

about the hard coded long short signal, i guess i just have to add 'randomExt' function to "short", and to ajust "long" with something like long: short + randomExt ?

**Comment by generalectric** [comment]
If I move timeout to config.. And out of main GA script.. When you update if you don't add the timeout option to your custom config gekkoga will error.. So keep an eye on Sample-config to get new additions and put them in your custom config to keep it up to date when updating gekkoga

**Comment by generalectric** [comment]
Oh and if you want to GA the macd settings just put randomExt.integer(50, 1),  instead of the hard coded number

**Comment by dinankou** [comment]
thanks ! and if i want to change the tested strategy (stochRSI, DEMA...), i just have to change line 33 ( stratName: 'MACD',), or is there other lines to modify ?

**Comment by generalectric** [comment]
Correct... There are no other lines to modify

**Comment by dinankou** [comment]
cool ! i'll try this tonight.
I want to run the genetic algorithm on this : https://github.com/askmike/gekko/issues/1275

it will need some configuration but it could be useful.

**Comment by generalectric** [comment]
Actually now that I think about it I believe I have timeout cranked up to something ridiculous. So this means it's capped at 2 minutes by default in uiconfig for your server. Edit the timeout setting there and restart server.js
