### ISSUE TITLE
Feature request : different coin pairs

### ISSUE THREAD

**Issue by zzmike76** [gekkowarez/gekkoga#31]
Hello

Would it be possible to add a feature to run GA analyses against multiple coin pairs?

e.g provide a list of coins in the config file and then run gekkoga in batch (creating different output files for each coin pairs)

assuming i am using the same strategy for every coin which requires different settings this would be very nice

thanks

**Comment by generalectric** [comment]
@zzmike76 I apologize for the late response. Yes its absolutely possible with some tweaking. I really dont want to get into this though as my hands are currently full. Its a good idea though!
