### ISSUE TITLE
Feature request: Gekkoga running default parameters at start as benchmark

### ISSUE THREAD

**Issue by shimanotaka** [gekkowarez/gekkoga#36]
I have email notifications enabled for new all time highs, but I keep getting notifications about ATHs that are worse than running the default values specified in the .toml. It would be nice if Gekkoga ran the defaults first and only notified me if it managed to do better than that result.

**Comment by sockRa** [comment]
How did you setup email notifications? I've seen the option but I do not quite understand how to set it up.

**Comment by shimanotaka** [comment]
I just entered my gmail address as receiver and sender in the part of the config file below and my gmail password. I guess the receiver email can be any email address.

   email: {
      enabled: true,
      receiver: 'myemail@gmail.com',
      senderservice: 'gmail',
      sender: 'myemail@gmail.com',
      senderpass: 'mygmailpassword',
    },

**Comment by generalectric** [comment]
@shimanotaka in order to do that you will have to run a quick epoch to create a json dropfile in results folder then edit the json dropfile and modify all the values to match those of your TOML and then edit the expected results for profit etc as well then start it back up.
