### ISSUE TITLE
Varied Backtesting Date Range

### ISSUE THREAD

**Issue by 0xPBIT** [gekkowarez/gekkoga#37]
Does the current setup of the GA operate on random intervals of the backtesting data? When I run the GA, I think the results are overfit for my backtesting data. Are there any ways of solving this issue?

**Comment by generalectric** [comment]
I myself have also sought out ways to prevent over fitting in both strat and gekkoga. Alot of this is your strat.. Though I believe it can be partially solved in gekkoga with a scoring system where less trades produces higher score. So if something had slightly higher profit but a ton more trades, less profit and less trades would have the higher score... To an extent obviously 10 trades with 0.2 btc profit wouldn't score higher than 100 btc profit with 1000 trades... And that is the hard part to wrap my head around, at least for me.
