### ISSUE TITLE
gekkoga is using 100% cpu

### ISSUE THREAD

**Issue by sanitariu** [gekkowarez/gekkoga#4]
Anyone knows why node run -c config/config.js is requesting data each second from gekko making the CPU on 100% ?
Is there any place we can change refresh interval or something like that ?

**Comment by generalectric** [comment]
Sorry for the late response. I made a commit in the develop branch to add parallelqueries parameter. Let me know if this helps.

**Comment by sanitariu** [comment]
Trying dev branch but it does not help. The problem is that gekkoga is requesting data each second repeating non-stop all of it. Its like a loop or something  making all cpus 100%. Maybe i miss something little although i did the installation 5 times already. I thought it must request data from gekko once each 5 minutes or so ?

**Comment by sanitariu** [comment]
For example: 
I see this each second in the console log of gekko
------------------------------
2017-11-14 12:12:27 (INFO):	Scanning local history for backtestable dateranges.
2017-11-14 12:12:27 (DEBUG):	Available 73
2017-11-14 12:12:27 (DEBUG):	Optimal 72
2017-11-14 12:12:27 (INFO):	Gekko is able to fully use the local history.
2017-11-14 12:12:27 (INFO):	Gekko was able to find a single daterange in the locally stored history:
2017-11-14 12:12:27 (INFO):		 from: 2017-11-14 08:58:00
2017-11-14 12:12:27 (INFO):		 to: 2017-11-14 10:10:00
2017-11-14 12:12:27 (INFO):	Scanning local history for backtestable dateranges.
2017-11-14 12:12:27 (INFO):	Scanning local history for backtestable dateranges.
2017-11-14 12:12:27 (INFO):		WARNING: BACKTESTING FEATURE NEEDS PROPER TESTING
2017-11-14 12:12:27 (INFO):		WARNING: ACT ON THESE NUMBERS AT YOUR OWN RISK!
------------------------

For data i have set:     "daterange: 'scan'," in the config file and i run watcher from gekko for USDT/ETH.
I also changed ETH in config.js file.
What i am doing wrong.

**Comment by dinankou** [comment]
maybe you should try shorten the date range, replace "scan" by 
from: 2017-11-14 08:58:00
to: 2017-11-14 10:10:00

or another date range corresponding to previously imported data.

I usually use 3 or 6 months of data at most.

**Comment by sanitariu** [comment]
I tried even setting to 1 hours. It still asking gekkoga each second non-stop. If i can help debug somehow just let me know.

**Comment by generalectric** [comment]
Did you run the first version of gekkoga.. If so did it have this same issue?

**Comment by sanitariu** [comment]
Yes i tried stable and develop versions. I am running on port 3002 and i use ip 192.168.1.129.
All this is changed in the config files. Gekko is reporting data and gekkoga is reporting information on the console but why it asks the same for the same period after one second very fast i do not know.

**Comment by generalectric** [comment]
This was fixed in New version of gekko in the develop branch. Clone gekko and checkout the develop branch and try it again using gekkoga develop 

*edit*
dont forget to restart server.js

**Comment by sanitariu** [comment]
I tried develop gekko + develop gekkoga and all variants around this. Also i tried on Mac OS. I tried with normal ports 3000 and host localhost and its absolutely the same. Requesting data many times per second making all CPUs to 100% on linux and macos. I even tried running market watch on USDT/ETH and then running this way:
....
const config = {
  gekkoConfig: {
    watch: {
      exchange: 'poloniex',
      currency: 'USDT',
      asset: 'ETH'
    },
    daterange: 'scan',
    //daterange: {
    //  from: '2017-07-01 00:00',
    //  to: '2017-09-07 00:00'
    //},

still 100%. Maybe i miss something ?

**Comment by generalectric** [comment]
So you're saying you did a fresh gekko clone and checked out the develop branch? And you are still showing the output from the api (server.js)?

**Comment by sanitariu** [comment]
Yes ! Everything fresh new on 2 systems. Node is version v8.9.0 on mac and v8.9.1 on linux (debian)
node server.js is giving output many times per second when i run on the second terminal gekkoga
making the CPU 100%. Maybe i can setup a machine for you to test it ?

**Comment by generalectric** [comment]
@sanitariu can you join us on [discord](https://discord.gg/cj34wxw)?

**Comment by sanitariu** [comment]
Actually after generalectric help i understood that this is normal. It is calculating many possibilities and when we see no improvement we can use the new strategy.
Thank you !
