### ISSUE TITLE
max parameters

### ISSUE THREAD

**Issue by dinankou** [gekkowarez/gekkoga#5]
hello again, 

I tried your GA on a DEMA strategy, making it working on short and long parameters : 
```
  stratName: 'DEMA',
  candleValues: [60,120],
  getProperties: () => ({
   // Here add the indicators and the ranges you want to handle
   // In this case my strategy wants to test RSI and MACD ranges
   historySize: 3,
   short: randomExt.integer(20, 5),
   long: randomExt.integer(30, 10),
  signal: 9,
   thresholds: {
     up: 0.025,
     down: -0.025,
   },
   candleSize: config.candleValues[randomExt.integer(config.candleValues.length -1, 0)]
  })
};
```

Here's the console log :

> Epoch number: 69
>     Time it took (seconds): 7.344
>     Max profit: 0.0026593000000709986 $ max profit position: 0
>     Max parametars:
>      { historySize: 3,
>   short: 5,
>   long: 24,
>   signal: 9,
>   thresholds: { up: 0.025, down: -0.025 },
>   candleSize: 120 }
>     Other metrics:
>      { balance: 0.012659300000070999,
>   profit: 0.0026593000000709986,
>   sharpe: 0.9521211772395055,
>   market: 48.95572263952417,
>   relativeProfit: 26.593000000709992,
>   yearlyProfit: '0.01260930',
>   relativeYearlyProfit: '126.09298054',
>   startPrice: 1197.00000001,
>   endPrice: 1783.00000001,
>   trades: 36 }
> 
>     --------------------------------------------------------------
>     Global maximum: 0.006328200000000001 $, parameters:
>      { historySize: 3,
>   short: 18,
>   long: 19,
>   signal: 9,
>   thresholds: { up: 0.025, down: -0.025 },
>   candleSize: 60 }
>     Other metrics of global maximum:
>     Global maximum so far:
>      { balance: 0.0163282,
>   profit: 0.006328200000000001,
>   sharpe: 4.7603449785054766,
>   market: 78.78028404194839,
>   relativeProfit: 63.28200000000001,
>   yearlyProfit: '0.02607705',
>   relativeYearlyProfit: '260.77052113',
>   startPrice: 1197.00000001,
>   endPrice: 2140,
>   trades: 23 }
>     --------------------------------------------------------------
> 
> 
>     --------------------------------------------------------------
>     Epoch number: 70
>     Time it took (seconds): 7.387
>     Max profit: 0.003414219999999999 $ max profit position: 3
>     Max parametars:
>      { historySize: 3,
>   short: 11,
>   long: 28,
>   signal: 9,
>   thresholds: { up: 0.025, down: -0.025 },
>   candleSize: 60 }
>     Other metrics:
>      { balance: 0.01341422,
>   profit: 0.003414219999999999,
>   sharpe: 0.5341688637892175,
>   market: 77.22857584897889,
>   relativeProfit: 34.1422,
>   yearlyProfit: '0.01358318',
>   relativeYearlyProfit: '135.83175251',
>   startPrice: 1197.00000001,
>   endPrice: 2121.42605293,
>   trades: 53 }
> 
>     --------------------------------------------------------------
>     Global maximum: 0.006328200000000001 $, parameters:
>      { historySize: 3,
>   short: 18,
>   long: 19,
>   signal: 9,
>   thresholds: { up: 0.025, down: -0.025 },
>   candleSize: 60 }
>     Other metrics of global maximum:
>     Global maximum so far:
>      { balance: 0.0163282,
>   profit: 0.006328200000000001,
>   sharpe: 4.7603449785054766,
>   market: 78.78028404194839,
>   relativeProfit: 63.28200000000001,
>   yearlyProfit: '0.02607705',
>   relativeYearlyProfit: '260.77052113',
>   startPrice: 1197.00000001,
>   endPrice: 2140,
>   trades: 23 }
>     --------------------------------------------------------------
> 
> 
>     --------------------------------------------------------------
>     Epoch number: 71
>     Time it took (seconds): 8.049
>     Max profit: 0.0023482316258675983 $ max profit position: 0
>     Max parametars:
>      { historySize: 3,
>   short: 11,
>   long: 28,
>   signal: 9,
>   thresholds: { up: 0.025, down: -0.025 },
>   candleSize: 120 }
>     Other metrics:
>      { balance: 0.012348231625867599,
>   profit: 0.0023482316258675983,
>   sharpe: 1.7577594135726766,
>   market: 49.07489853927257,
>   relativeProfit: 23.48231625867598,
>   yearlyProfit: '0.01109431',
>   relativeYearlyProfit: '110.94306848',
>   startPrice: 1197.00000001,
>   endPrice: 1784.42653553,
>   trades: 28 }
> 
>     --------------------------------------------------------------
>     Global maximum: 0.006328200000000001 $, parameters:
>      { historySize: 3,
>   short: 18,
>   long: 19,
>   signal: 9,
>   thresholds: { up: 0.025, down: -0.025 },
>   candleSize: 60 }
>     Other metrics of global maximum:
>     Global maximum so far:
>      { balance: 0.0163282,
>   profit: 0.006328200000000001,
>   sharpe: 4.7603449785054766,
>   market: 78.78028404194839,
>   relativeProfit: 63.28200000000001,
>   yearlyProfit: '0.02607705',
>   relativeYearlyProfit: '260.77052113',
>   startPrice: 1197.00000001,
>   endPrice: 2140,
>   trades: 23 }
>     --------------------------------------------------------------
> 
> 
>     --------------------------------------------------------------
>     Epoch number: 72
>     Time it took (seconds): 7.579
>     Max profit: 0.0034560800000000003 $ max profit position: 0
>     Max parametars:
>      { historySize: 3,
>   short: 11,
>   long: 25,
>   signal: 9,
>   thresholds: { up: 0.025, down: -0.025 },
>   candleSize: 60 }
>     Other metrics:
>      { balance: 0.01345608,
>   profit: 0.0034560800000000003,
>   sharpe: 0.5121780203231062,
>   market: 77.22857584897889,
>   relativeProfit: 34.5608,
>   yearlyProfit: '0.01374971',
>   relativeYearlyProfit: '137.49711595',
>   startPrice: 1197.00000001,
>   endPrice: 2121.42605293,
>   trades: 59 }
> 
>     --------------------------------------------------------------
>     Global maximum: 0.006328200000000001 $, parameters:
>      { historySize: 3,
>   short: 18,
>   long: 19,
>   signal: 9,
>   thresholds: { up: 0.025, down: -0.025 },
>   candleSize: 60 }
>     Other metrics of global maximum:
>     Global maximum so far:
>      { balance: 0.0163282,
>   profit: 0.006328200000000001,
>   sharpe: 4.7603449785054766,
>   market: 78.78028404194839,
>   relativeProfit: 63.28200000000001,
>   yearlyProfit: '0.02607705',
>   relativeYearlyProfit: '260.77052113',
>   startPrice: 1197.00000001,
>   endPrice: 2140,
>   trades: 23 }
>     --------------------------------------------------------------

So if im correct, the recomended parameters for DEMA strategy is short 18 long 19 on 60 minutes candles ?

**Comment by generalectric** [comment]
With the tresholds you have, yes... for different results you could do randomext float on the thresholds.
