### ISSUE TITLE
No trades happening

### ISSUE THREAD

**Issue by battlezone100** [gekkowarez/gekkoga#6]
I have ran Gekkoga for quite a while (over 1000 epochs) on a dataset of about 5 months with random numbers for most variables. However, there hasn't been a single strategy that did any trades. If I backtest via the webGUI, I do get trades. Any ideas?

**Comment by dinankou** [comment]
Usually i have this issue when i'm runing MACD based strategies with too high thresholds, such as 0.05 / -0.05.

Try lowering the thresholds a thousandfold, it might solve the problem.

**Comment by battlezone100** [comment]
Last time I tried with both thresholds at 0 but still no trading happening. If I input the same values in the backtesting on the webGUI, I do see trades.

When I try to run DEMA instead of MACD it does work. Very strange.

**Comment by thisisloze** [comment]
Yeah seems to ONLY work with DEMA. I cant get it to work on MACD or RSI or any other strat.

**Comment by ddey94** [comment]
Even with DEMA, I can not get this to work. It was working yesterday though. I re copied the parameters and lowered them a thousandfold, but no luck.

**Comment by talentoscope** [comment]
I can confirm this behaviour too. MACD epochs result in 0 trades, regardless of config settings. DEMA works just fine.

**Comment by generalectric** [comment]
use ppo instead of macd.... its basically macd percentage. Youre getting 0 trades because the bidprice for that asset is so small your threshold randoms arent trying numbers between 0.00000015 and 0.00000004.

**Comment by padioca** [comment]
I have tried MACD, DEMA, RSI and PPO and cannot get any of them to trade and none of them match what is being output when I run a backtest in Gekko.  Any ideas?  Using Gekko 0.5.8 with the latest version of Gekko GA
