### ISSUE TITLE
Bitstamp data causing problem?

### ISSUE THREAD

**Issue by maxiedaniels** [gekkowarez/gekkoga#8]
I used bitcoin-scraper (as instructed on the gekkowarez page) to download 2011 - 2017 bitstamp BTC/USD data. It went through the whole process of downloading, then fixing the holes, and then ended up spitting out a ~250 megabyte DB file. I threw that into gekko, and tried gekko's backtesting feature, and that worked great.

I then tried to use gekkoga on that data, and it's giving me strange errors - gekko keeps dying, and the error given on gekkoga is a 500 internal service error.

Any idea what could cause this? I'm not seeing any other useful information...

**Update**

I forgot to mention, I'm only using the 2017 part of the data to backtest against. The strange part is that the backtesting works great in Gekko...

**Comment by generalectric** [comment]
Did you get it working?

**Comment by maxiedaniels** [comment]
Ah - yes my apologies for not updating. It turns out the minute was auto filling in slightly later than I had data for. My bad!
